### ISSUE TITLE
Error when I start the game

### ISSUE THREAD

**Issue by Obaminha13** [mspielberg/factorio-beltlayer#5]
Hello,
I have this error when I start the game: https://imgur.com/a/GUas4zz

**Comment by mspielberg** [comment]
Could you please post your mod-list.json and mod-settings.dat?

**Comment by Obaminha13** [comment]
[mods.zip](https://github.com/mspielberg/factorio-beltlayer/files/5012552/mods.zip)

**Comment by mspielberg** [comment]
I can't reproduce the crash. Could you post your `factorio-current.log` right after the error happens? Are you running custom versions of any of these mods? Which version of Factorio are you running?

**Comment by Obaminha13** [comment]
I downloaded the mod here (github), and the Factorio version is 0.18.31

[factorio-current.log](https://github.com/mspielberg/factorio-beltlayer/files/5013593/factorio-current.log)

**Comment by mspielberg** [comment]
Please download only from the portal. The master branch here on Github may have experimental code, non-working code, etc. Are you still experiencing the problem with v1.0.0 of Factorio?
