### ISSUE TITLE
Inconsistent flow behavior

### ISSUE THREAD

**Issue by initbar** [mspielberg/factorio-beltlayer#9]
### Environment

- **Factorio**: v1.0.0 (build 54889, win64, steam)
- **beltlayer**: v1.0.3
- **Mods**:

![Screenshot_2021-01-16_19-23-04](https://user-images.githubusercontent.com/12630151/104827836-4c7f0780-5830-11eb-8f92-dc35a096ac7e.png)

### Bug

I have a design where two iron ore harvesting system are passed into underground track:

![Screenshot_2021-01-16_19-08-18](https://user-images.githubusercontent.com/12630151/104827712-dc23b680-582e-11eb-9085-70bcfcd078da.png)

Two belts are then split. As you can see, up to here, the belts are transporting 100% of the ores.

![Screenshot_2021-01-16_19-08-33](https://user-images.githubusercontent.com/12630151/104827713-dcbc4d00-582e-11eb-9711-a72a07830ba7.png)

Once the belts resurface, however, there is approximately ~50% loss where ores are released in a noticeable boolean pattern of "on" and "off". There isn't any distinguishable impediments where the losses can occur, so my guess is that there is a bug. The lossy block size seems to be constant 20.

![Screenshot_2021-01-16_19-11-40](https://user-images.githubusercontent.com/12630151/104827714-dd54e380-582e-11eb-93a9-4717c2b4ed78.png)

A zoomed screenshot without annotations:

![Screenshot_2021-01-16_19-19-13](https://user-images.githubusercontent.com/12630151/104827829-2b1e1b80-5830-11eb-97c1-943645f1c8a7.png)

**Comment by initbar** [comment]
Incidentally, it looks like the latest version is [v2.0.3](https://github.com/mspielberg/factorio-beltlayer/releases/tag/v2.0.3), but Factorio's mod indicates [v1.0.3](https://github.com/mspielberg/factorio-beltlayer/releases/tag/v1.0.3) to be the latest.

**Comment by mspielberg** [comment]
I’m not sure why you’re seeing that behavior. Can you try increasing the buffer size in the mod options?

To run beltlayer 2.0 or later you must be running the experimental 1.1.x series of Factorio. This is accessible via the Steam betas page, or the options of the game for standalone versions.

**Comment by initbar** [comment]
I think found it. After a bit of experimentation, the underground splitting seems to be what's causing the ~50% loss. If there is a non-split, direct path from origin to destination, the transported items are fully preserved.
